export const STRATEGIES = [
  "Abandona los instrumentos habituales",
  "Acepta el consejo",
  "Acreción (crecimiento o aumento de tamaño de un cuerpo, estructura o terreno mediante la adición, acumulación o deposición gradual de materia externa)",
  "Una línea tiene dos lados",
  "Permítete una concesión (una concesión es el abandono de una restricción)",
  "¿Hay secciones? Considera las transiciones",
  "Pídele a la gente que trabaje en contra de su mejor criterio",
  "Pregúntale a tu cuerpo",
  "Reúne algunos instrumentos en un grupo y trata el grupo como unidad",
  "Equilibra el principio de consistencia con el de inconsistencia",
  "Sé sucio",
  "Respira más profundo",
  "Puentes —construir— quemar",
  "Cascadas",
  "Cambia los roles de los instrumentos",
  "No cambies nada y continúa con una consistencia impecable",
  "Voces de niños —hablando— cantando",
  "Análisis de clusters",
  "Considera distintos sistemas de fundido",
  "Consulta otras fuentes —prometedoras— no prometedoras",
  "Convierte un elemento melódico en rítmico",
  "¡Coraje!",
  "Corta una conexión vital",
  "Decora, decora",
  "Define un área como «segura» y úsala como ancla",
  "Destruye —nada— lo más importante",
  "Descarta un axioma",
  "Desconéctate del deseo",
  "Descubre las recetas que estás usando y abandónalas",
  "Distorsión del tiempo",
  "No hagas nada el mayor tiempo posible",
  "No le temas a las cosas por ser fáciles de hacer",
  "No le temas a los clichés",
  "No tengas miedo de mostrar tus talentos",
  "No rompas el silencio",
  "No enfatices una cosa más que otra",
  "Haz algo aburrido",
  "Lava los platos",
  "¿Las palabras necesitan cambiar?",
  "¿Necesitamos huecos?",
  "Enfatiza las diferencias",
  "Enfatiza las repeticiones",
  "Enfatiza las fallas",
  "Ante una elección, haz las dos (de Dieter Roth)",
  "Introduce grabaciones en una situación acústica",
  "Llena cada beat con algo",
  "Date un masaje en el cuello",
  "Ecos fantasma",
  "Revela el juego",
  "Cede ante tu peor impulso",
  "Ve despacio por todo el borde exterior",
  "Honra tu error como una intención oculta",
  "¿Cómo lo hubieras hecho?",
  "Humaniza algo libre de error",
  "Imagina la música como una cadena o una oruga en movimiento",
  "Imagina la música como un conjunto de eventos desconectados",
  "Gradaciones infinitesimales",
  "Intenciones —credibilidad— nobleza— humildad",
  "Hacia lo imposible",
  "¿Está terminado?",
  "¿Falta algo?",
  "¿La afinación es la adecuada?",
  "Simplemente continúa",
  "Canal izquierdo, canal derecho, canal central",
  "Escucha en total oscuridad, o en una sala muy grande, muy en silencio",
  "Escucha la voz quieta",
  "Mira un objeto muy pequeño; mira su centro",
  "Mira el orden en que haces las cosas",
  "Mira de cerca los detalles más incómodos y amplíficalos",
  "Control del mínimo común denominador —un beat— una nota— un riff",
  "Haz valioso un espacio vacío poniéndolo en un marco exquisito",
  "Haz una lista exhaustiva de todo lo que podrías hacer y haz lo último de la lista",
  "Haz una acción súbita, destructiva, impredecible; incorpórala",
  "Mecaniza algo idiosincrático",
  "Silencia y continúa",
  "Solo un elemento de cada tipo",
  "Maquinaria (orgánica)",
  "Resiste el cambio abiertamente",
  "Ponte tapones en los oídos",
  "Recuerda esas tardes tranquilas",
  "Elimina ambigüedades y convierte en especificidades",
  "Elimina especificidades y convierte en ambigüedades",
  "La repetición es una forma de cambio",
  "Al revés",
  "Cortocircuito",
  "Cierra la puerta y escucha desde afuera",
  "Sustracción simple",
  "Análisis espectral",
  "Toma un descanso",
  "Quita los elementos en orden de aparente no-importancia",
  "Tápate la boca con cinta (de Ritva Saarikko)",
  "El principio de inconsistencia",
  "La cinta ahora es la música",
  "Piensa en la radio",
  "Ordena",
  "Confía en quien eres ahora mismo",
  "Dale la vuelta",
  "Tuerce la columna",
  "Usa una idea vieja",
  "Usa un color inaceptable",
  "Usa menos notas",
  "Usa filtros",
  "Usa personas «no calificadas»",
  "Agua",
  "¿En qué estás pensando realmente ahora mismo? Incorpóralo",
  "¿Cuál es la realidad de la situación?",
  "¿Qué errores cometiste la última vez?",
  "¿Qué haría tu amigo más cercano?",
  "¿Qué no harías?",
  "Trabaja a una velocidad diferente",
  "Eres un ingeniero",
  "Solo puedes hacer un punto a la vez",
  "No tienes que avergonzarte de usar tus propias ideas"
];
